### PR TITLE
Rename approved state to ready

### PR DESCRIPTION
**Pull request by thehenster**
We're renaming our 'approved' state to 'ready' which has more meaning to people who write content'n'stuff.

https://trello.com/c/wifM3m50

### CODE REVIEW

**Comment by AndrewVos** [comment]
@thehenster where's ya migrations?

**Comment by thehenster** [comment]
Yikes. Thanks.

**Comment by thehenster** [comment]
@AndrewVos ^^ :sparkles:

**Comment by AndrewVos** [comment]
lgtm

**Pull request merged**
