### PR TITLE
Revamp guide publishing process

### PR DESCRIPTION
**Pull request by tadast**
> As a content designer
I need to have a clear action to publish content or send it back for more edits
So that I can publish and review content easily

Research on other publishing apps has shown that having the publish button on the same screen a the editable fields is confusing.

We should make publishing a distinct action, or allow someone reviewing the document to send it back for more changes.

This screen should show:

- Preview of the page (non editable).

- The change note (non editable).

- Publish button.

- Option to edit.

Ideally this page should also show "Needs more work" button (send it back to draft state), but I've opted not to introduce this feature in this branch as it can currently be substituted by comments and edit draft option. I didn't want to make this PR too big.

We also don't have final designs for this feature, so this simply attempts to put information where we thing it should be displayed and do the styling later.

screenshot 2015-11-06 15 45 42

### CODE REVIEW

**Comment by AndrewVos** [comment]
lgtm

**Comment by tadast** [comment]
@AndrewVos thanks for looking at this. I've added a couple more commits to this PR, can you have a look at them please?

**Comment by AndrewVos** [comment]
@tadast reviewed. lgtm. I would merge this now but now 100% sure you're ready to go. Feel free to merge.

**Comment by tadast** [comment]
:cool: I'll address your comments and merge myself, I don't think they need to be reviewed again as they are quite minor.

**Pull request merged**
