### PR TITLE
Use service manual frontend

### PR DESCRIPTION
**Pull request by thehenster**
Only when we are ready to start republishing to the new frontend should this be merged and deployed.

### CODE REVIEW

**Comment by dougdroper** [comment]
:+1:

**Comment by thehenster** [comment]
Hey @AndrewVos. I deployed this branch to integration and it seems to be behaving. Merging this will stop us deploying the publisher to production until the new frontend is in production.. But it should be this week. Merge or hold off?

**Comment by AndrewVos** [comment]
Why would it stop us deploying the new publisher @thehenster?

**Comment by thehenster** [comment]
This changes the rendering_app to be service-manual-frontend. If we deploy the publisher, publish something and try and view it in the frontend it won't be able to find the rendering app service-manual-frontend.

As we're on the home straight with the frontend I think it's worth it so we can get more integration testing under our belt.. but asked in case you might have something you're keen to get out?

**Comment by AndrewVos** [comment]
No I don't have anything pressing. Are we really ready to release the new frontend though? I think that should be deployed before this gets merged.

**Comment by thehenster** [comment]
The only benefit is a bit of extra testing in integration. No bother at all though.. let's leave it.

**Pull request merged**
