### PR TITLE
Configure gds-sso

### PR DESCRIPTION
**Pull request by tadast**
Require authentication via signon in order to access anything in this application. I've not set up permission rules for now as we don't know the logic for that yet.

@KushalP can you have a look at this, paying some extra attention to the ops parts: is there any configuration missing, do we need to modify deploy scripts or create a trello task for setting up tokens in signotron2 in all environments?

### CODE REVIEW

**Comment by KushalP** [comment]
There's already a story in progress to create the relevant tokens in all environments: https://trello.com/c/q5SC0Eqk

**Comment by KushalP** [comment]
This all looks good to me. One thing I'd add is a comment to the top of `config/initializers/gds-sso.rb` saying that it will be overwritten on deploy.

**Comment by tadast** [comment]
Would it be ok to add the comment you mentioned and push directly to master given that's the only change?

**Comment by KushalP** [comment]
Don't worry about that last comment. We're moving to 12-Factor apps so these can be injected as ENV vars.

**Pull request merged**
