### PR TITLE
Document the guide's nested URL structure

### PR DESCRIPTION
**Pull request by thehenster**
I'd like to get Sean's feedback on the performance analysis section..

### CODE REVIEW

**Comment by thehenster** [comment]
Hi @deborahchua and @36degrees,

I _was_ going to add an additional bit to this doc about a type of content that doesn't have a topic which is just emerging now. However, it is just emerging, so I'd rather merge this now and add to it later if it becomes a thing.

👀 welcome on this!

**Comment by thehenster** [comment]
Sean has OK'd the performance section btw.

**Comment by 36degrees** [comment]
Mentioned yesterday about the 'workaround' for changing a URL (unpublishing, cloning to a new guide) having undesirable side effects, e.g. loss of edit history. Worth fleshing that out a bit? At the minute it just sounds like it's a faff.

**Comment by thehenster** [comment]
Sure :+1:. Coming up.

**Comment by thehenster** [comment]
I've added an extra point about maintaining additional redirects too..

**Comment by 36degrees** [comment]
LGTM 👍

**Pull request merged**
