### PR TITLE
Use search index mainstream with document type service_manual

### PR DESCRIPTION
**Pull request by thehenster**
So that we don't share the same index as the original service manual, which is purged upon each deploy, we are going to use the mainstream index and a specific document type so that search queries can downgrade service manual results (as per current functionality).

Here is the related PR in rummager for the new document type and the downgrading bit: https://github.com/alphagov/rummager/pull/586

### CODE REVIEW

**Comment by thehenster** [comment]
Updated to always using the format "service_manual" and the _type "service_manual".

**Comment by rboulton** [comment]
Is there a difference in the data stored in a "service_manual" document, compared to a "manual_section" document?  I'm assuming not, since you're not changing the data sent along with this change.  It's desirable not to unneccesarily increase the number of formats which exist, since that makes rummager's job more complex, and makes it harder to do things like changing the way all manuals work.

If you _do_ decide to introduce a new format, it will.  I also think it should be named "service_manual_section", since it's not the whole manual.  (For the existing modelling, there's a "manual" format, which multiple "manual_sections" are then part of.)

If you're just wanting to change the weight of documents in the service manual, that could be accomplished by looking at the value of the "manual" field for each document, and downweighting ones which have the value "service-manual".  This would be a more generic and extensible approach for the future (all manuals may need weighting according to the importance of the manuals).  This may also not be required, since the popularity weighting does this type of effect for all formats.

**Comment by AndrewVos** [comment]
@rboulton Does the "manual" type exist on mainstream?

**Comment by rboulton** [comment]
Yes - for example: https://www.gov.uk/api/search.json?filter_link=/guidance/immigration-rules

(Just had a face-to-face chat with @tijmenb who comments, reasonably, that keeping the downweighting code simple is much easier if you introduce a new format for service manual documents, so that might well be the way to go.  I'd still suggest using "service_manual_section" as the format name instead of "service_manual", though.)

**Comment by AndrewVos** [comment]
I think a name that applies to our project might be `service_manual_guide`?

**Comment by AndrewVos** [comment]
Actually, does this include topics too? Maybe `service_manual_section` is the one!

**Comment by thehenster** [comment]
If we do go with the format `service_manual_section` should we also create `service_manual` which would have a single document to represent the whole service manual? If so should we down weight this single document's format `service_manual` too? Personally, I don't think so. The service manual itself seems sufficiently important.

Also, I think I overlooked adding the new format(s) to https://github.com/alphagov/rummager/blob/master/config/schema/indexes/mainstream.json

**Comment by thehenster** [comment]
I don't know the query language for elastic search. But if we were to consider the code changes to down weight via the "manual" value. Would this do it? https://github.com/alphagov/rummager/commit/dd0c2186c514e19b0f3574a7612da47625108a1c

**Comment by thehenster** [comment]
Closing in favour of https://github.com/alphagov/service-manual-publisher/pull/191

**Pull request closed without merging**
